baseURL = 'https://smartzhuo.github.io/'
languageCode = 'en-us'
title = 'Zhuo is here'
theme = 'ananke'
pygmentsCodeFences = true
pygmentsUseClasses = true


[params]
  author = 'Zhuo'
  description = "å…¨èƒ½å°ç™½"
  email = 'zhuonbg@gmail.com'
  phone = '+49 176-8593-3340'
  rss = true
  lastmod = true
  userStatusEmoji = "ğŸ˜€"
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "Germany"
  enableGitalk = true
